stages:
  train:
    cmd: mkdir models && echo 1234 > models/best.ckpt
    deps:
    - data/raw
    params:
    - foo
    outs:
    - models
  inference:
    cmd: mkdir predictions && echo 4321 > predictions/pred.txt
    deps:
    - data/raw
    - models
    params:
    - bar
    outs:
    - predictions
